CREATE TABLE IF NOT EXISTS MPA_RATING (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS GENRES (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(200),
    RELEASEDATE DATE,
    DURATION INT CHECK (DURATION > 0),
    MPARATINGID BIGINT,
    FOREIGN KEY (MPARATINGID) REFERENCES MPA_RATING(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_FILM_LIKES (
    USERID BIGINT,
    FILMID BIGINT,
    PRIMARY KEY (USERID, FILMID),
    FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FILMID) REFERENCES FILMS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_FRIENDS (
    USERID BIGINT,
    FRIENDID BIGINT,
    STATUS VARCHAR(255) NOT NULL DEFAULT 'unconfirmed',
    PRIMARY KEY (USERID, FRIENDID),
    FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FRIENDID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
    FILMID BIGINT,
    GENREID BIGINT,
    PRIMARY KEY (FILMID, GENREID),
    FOREIGN KEY (FILMID) REFERENCES FILMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (GENREID) REFERENCES GENRES(ID) ON DELETE CASCADE
);